SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `Books`;
DROP TABLE IF EXISTS `Help`;
DROP TABLE IF EXISTS `Requested_books`;
DROP TABLE IF EXISTS `Staff`;
DROP TABLE IF EXISTS `Students`;
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 1;
